### ISSUE TITLE
nonstandard ssh key location

### ISSUE THREAD

**Issue by laino** [cyradotpink/russhian-roulette#1]
I have multiple keys stored in ``.ssh/keys/*``. The path this script tries to access doesn't exist.

Please add a configuration parameter and a way to post multiple keys.

**Comment by paulidale** [comment]
Post **all** keys in that directory.  Might as well do the job properly.

**Comment by cyradotpink** [comment]
Finally deciding to close this because I wrote this script as a joke, and I have no intention for it to ever be complete or robust in any way. Of course I'll happily accept PRs :3
